# Generated by Django 5.0.6 on 2024-06-10 14:22

import django.db.models.deletion
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressCell',
            fields=[
                ('progress_cell_id', models.AutoField(default=project.models.ProgressCell.number, editable=False, primary_key=True, serialize=False)),
                ('progress_cell_title', models.CharField(max_length=100)),
                ('progress_cell_description', models.TextField(default='no description')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressCellDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('progress_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.progresscell')),
            ],
            options={
                'unique_together': {('progress_cell', 'file')},
            },
        ),
    ]
