# Generated by Django 5.0.6 on 2024-06-13 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresscell',
            name='progress_cell_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 5, 25, 31, 405187, tzinfo=datetime.timezone.utc)),
        ),
    ]
