# Generated by Django 5.0.6 on 2024-06-10 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresscell',
            name='progress_cell_upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
