# Generated by Django 5.0.6 on 2024-05-23 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantCertifiedDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.applicant')),
            ],
            options={
                'unique_together': {('applicant', 'image')},
            },
        ),
    ]
